# Night Owl Theme for Alacritty

# Indexed Colors
[[colors.indexed_colors]]
color = "#f8a068"  # Custom indexed color
index = 16

[[colors.indexed_colors]]
color = "#f4d9cd"  # Custom indexed color
index = 17

# Bright colors
[colors.bright]
black = "#011627"
red = "#EF5350"
green = "#22DA6E"
yellow = "#addb67" # Using the editor's selection color for bright yellow
blue = "#82AAFF"
magenta = "#C792EA"
cyan = "#21c7a8" # Using the editor's string color for bright cyan
white = "#ffffff"

# Cursor color
[colors.cursor]
text = "#ffffff"
cursor = "#c792ea"

# Dim colors (same as normal because Night Owl doesn't specify dim colors)
[colors.dim]
black = "#011627"
red = "#EF5350"
green = "#22DA6E"
yellow = "#addb67"
blue = "#82AAFF"
magenta = "#C792EA"
cyan = "#21c7a8"
white = "#ffffff"

# Normal colors
[colors.normal]
black = "#011627"
red = "#EF5350"
green = "#22DA6E"
yellow = "#addb67"
blue = "#82AAFF"
magenta = "#C792EA"
cyan = "#21c7a8"
white = "#ffffff"

# Primary colors
[colors.primary]
background = "#011627"
foreground = "#d6deeb"

# Bright foreground for extra contrast against the dark background
bright_foreground = "#d6deeb"
dim_foreground = "#d6deeb"

# Hints
[colors.hints.end]
background = "#7e57c2"
foreground = "#edecee"

[colors.hints.start]
background = "#c792ea"
foreground = "#edecee"

# Search
[colors.search.focused_match]
background = "#addb67"
foreground = "#011627"

[colors.search.matches]
background = "#7e57c2"
foreground = "#edecee"

# Footer bar
[colors.footer_bar]
background = "#011627"
foreground = "#ffffff"

# Selection
[colors.selection]
background = "#5f7e97"
text = "#ffffff"

# Vi mode cursor
[colors.vi_mode_cursor]
cursor = "#c792ea"
text = "#ffffff"
