[[colors.indexed_colors]]
color = "#f8a068"
index = 16

[[colors.indexed_colors]]
color = "#f4d9cd"
index = 17

[colors.bright]
black = "#46464e"
blue = "#7da0b5"
cyan = "#82c9a0"
green = "#9ac47a"
magenta = "#f3b8d0"
red = "#f4688a"
white = "#909297"
yellow = "#fad78c"

[colors.cursor]
cursor = "#f4d9cd"
text = "#0c0c10"

[colors.dim]
black = "#36363d"
blue = "#7da0b5"
cyan = "#82c9a0"
green = "#9ac47a"
magenta = "#f3b8d0"
red = "#f4688a"
white = "#a7a9b4"
yellow = "#fad78c"

[colors.hints.end]
background = "#909297"
foreground = "#0c0c10"

[colors.hints.start]
background = "#fad78c"
foreground = "#0c0c10"

[colors.normal]
black = "#36363d"
blue = "#7da0b5"
cyan = "#82c9a0"
green = "#9ac47a"
magenta = "#f3b8d0"
red = "#f4688a"
white = "#a7a9b4"
yellow = "#fad78c"

[colors.primary]
background = "#1a1a20"
bright_foreground = "#c1c4ce"
dim_foreground = "#c1c4ce"
foreground = "#c1c4ce"

[colors.search.focused_match]
background = "#9ac47a"
foreground = "#0c0c10"

[colors.footer_bar]
background = "#909297"
foreground = "#0c0c10"

[colors.search.matches]
background = "#909297"
foreground = "#0c0c10"

[colors.selection]
background = "#f4d9cd"
text = "#0c0c10"

[colors.vi_mode_cursor]
cursor = "#a9a4e1"
text = "#0c0c10"

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font]
size = 15.0

[env]
TERM = "alacritty"

[keyboard]
bindings = [
  { key="v", mods="SUPER", action="Paste" },
  { key="c", mods="SUPER", action="Copy" },
]

