import = ['~/.config/alacritty/themes/custom-theme.toml']

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font]
size = 15.0

[env]
TERM = "alacritty"

[keyboard]
bindings = [
  { key="v", mods="SUPER", action="Paste" },
  { key="c", mods="SUPER", action="Copy" },
]

