import = ['~/.config/alacritty/themes/rose-pine-moon.toml']

[font.bold]
# family = "JetBrains Mono Nerd Font"
family = "MonaspiceNe NFM"

[font.italic]
# family = "JetBrains Mono Nerd Font"
family = "MonaspiceNe NFM"

[font.normal]
# family = "JetBrains Mono Nerd Font"
family = "MonaspiceNe NFM"

[font]
size = 17.0

[env]
TERM = "alacritty"

[keyboard]
bindings = [
  { key="v", mods="SUPER", action="Paste" },
  { key="c", mods="SUPER", action="Copy" },
]

