[colors.primary]
background = '#f7f9ff'
foreground = '#181c20'

[colors.selection]
text = '#181c20'
background = '#e3f2fd'

[colors.cursor]
text = '#f7f9ff'
cursor = '#1976d2'

[colors.normal]
black   = '#101418'
red     = '#c7003b'
green   = '#009d14'
yellow  = '#fbee00'
blue    = '#1077dc'
magenta = '#b7dbff'
cyan    = '#1976d2'
white   = '#36383a'

[colors.bright]
black   = '#000105'
red     = '#fb1e60'
green   = '#07e724'
yellow  = '#fff100'
blue    = '#077df1'
magenta = '#b7dbff'
cyan    = '#8ec7ff'
white   = '#f6faff'
